version: "2.4"

services:
  test-sagemaker:
    image: "youyakuman:cpu_inference_0.9"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./src/server/:/opt/ml/model/code
      - ./model/:/opt/ml/model/code/models
    command: bash /opt/ml/model/code/test_youyakuman.sh

  client:
    image: youyakuman-client
    build:
      context: ./docker/client
      dockerfile: ./Dockerfile.client
    environment: 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-default}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-default}
    container_name: youyakuman-client
    volumes:
      - ./src/client:/workspace/code
    ports:
      - "8501:8501" # using by streamlit
    command: bash entry.sh

  setup:
    image: youyakuman-setup
    build:
      context: ./docker/setup
      dockerfile: ./Dockerfile.setup
    environment: 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-default}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-default}
    container_name: youyakuman-setup
    volumes: 
      - ./src/setup:/workspace/code
      - ./src/server:/workspace/code/server
    network_mode: "host"
    command: bash setup.sh
